const types = {
  AUTH_USER_REQUEST: '@auth/AUTH_USER_REQUEST',
  AUTH_USER_SUCCEESS: '@auth/AUTH_USER_SUCCEESS',
  AUTH_USER_FAILURE: '@auth/AUTH_USER_FAILURE',

  AUTH_USER_EMPTY: '@auth/AUTH_USER_EMPTY',
};

export default types;
